"""Convert the UVH-26 COCO annotations into the YOLO layout ultralytics trains on.

Produces:
    <out>/labels/{train,val}/<image_id>.txt   -- one "<cls> <cx> <cy> <w> <h>" line per box, normalized
    <out>/uvh26.yaml                           -- ultralytics data config (14 classes)

COCO category ids are 1-based (Hatchback=1 .. Others=14); YOLO wants 0-based
contiguous class indices, so everything shifts down by one. Class *order* is
preserved exactly as the dataset defines it, so a trained checkpoint's
names[] lines up with the dataset's own taxonomy.

Boxes are COCO [x, y, w, h] in absolute pixels with the origin at the top-left;
YOLO wants normalized center-x/center-y/width/height. Degenerate or
out-of-frame boxes are clipped and dropped if they survive with no area.

Usage:
    env/bin/python scripts/opencv_heuristic/uvh26_prepare.py --root data/uvh26
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path

SPLIT_JSON = {"train": "UVH-26-MV-Train.json", "val": "UVH-26-MV-Val.json"}


def parse_args(argv=None):
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--root", type=Path, default=Path("data/uvh26"),
                    help="dir holding the downloaded jsons and images/{train,val}/")
    return p.parse_args(argv)


def convert_split(root: Path, split: str) -> tuple[int, int, Counter, list]:
    coco = json.loads((root / SPLIT_JSON[split]).read_text())

    categories = sorted(coco["categories"], key=lambda c: c["id"])
    id_to_idx = {c["id"]: i for i, c in enumerate(categories)}  # 1-based -> 0-based

    images = {im["id"]: im for im in coco["images"]}
    by_image = defaultdict(list)
    for ann in coco["annotations"]:
        by_image[ann["image_id"]].append(ann)

    label_dir = root / "labels" / split
    label_dir.mkdir(parents=True, exist_ok=True)
    img_dir = root / "images" / split

    class_counts = Counter()
    written = 0
    dropped = 0
    missing_images = []

    for image_id, im in images.items():
        file_name = Path(im["file_name"]).name
        if not (img_dir / file_name).exists():
            missing_images.append(file_name)
            continue

        w_img, h_img = float(im["width"]), float(im["height"])
        lines = []
        for ann in by_image.get(image_id, []):
            if ann.get("iscrowd"):
                continue
            x, y, w, h = (float(v) for v in ann["bbox"])
            # clip to frame, then drop anything with no area left
            x1, y1 = max(0.0, x), max(0.0, y)
            x2, y2 = min(w_img, x + w), min(h_img, y + h)
            if x2 <= x1 or y2 <= y1:
                dropped += 1
                continue
            cx, cy = (x1 + x2) / 2.0 / w_img, (y1 + y2) / 2.0 / h_img
            bw, bh = (x2 - x1) / w_img, (y2 - y1) / h_img
            idx = id_to_idx[ann["category_id"]]
            class_counts[categories[idx]["name"]] += 1
            lines.append(f"{idx} {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}")

        # images with no boxes still get an empty label file: ultralytics treats
        # them as valid background negatives rather than missing labels.
        (label_dir / f"{Path(file_name).stem}.txt").write_text("\n".join(lines))
        written += 1

    return written, dropped, class_counts, missing_images


def main(argv=None) -> int:
    args = parse_args(argv)
    root = args.root.resolve()

    coco = json.loads((root / SPLIT_JSON["train"]).read_text())
    categories = sorted(coco["categories"], key=lambda c: c["id"])
    names = [c["name"] for c in categories]

    total_counts = Counter()
    for split in ("train", "val"):
        written, dropped, counts, missing = convert_split(root, split)
        total_counts.update(counts)
        print(f"[{split}] wrote {written} label files, dropped {dropped} degenerate boxes, "
              f"{len(missing)} images referenced by the json but missing on disk")
        if missing[:3]:
            print(f"   e.g. missing: {missing[:3]}")

    yaml_path = root / "uvh26.yaml"
    yaml_lines = [
        "# UVH-26 (Urban Vision Hackathon) -- India traffic-camera vehicle detection.",
        "# Generated by uvh26_prepare.py; class order matches the dataset's COCO categories.",
        f"path: {root}",
        "train: images/train",
        "val: images/val",
        "",
        "names:",
    ] + [f"  {i}: {n}" for i, n in enumerate(names)]
    yaml_path.write_text("\n".join(yaml_lines) + "\n")

    print(f"\nWrote {yaml_path}")
    print("\nBox counts by class:")
    for n in names:
        print(f"  {n:18s} {total_counts.get(n, 0):>8d}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
