disable_subclassifiers: true
model:
  confidence: 0.35
  device: cuda:0
  imgsz: 640
  tracker: bytetrack.yaml
  yolo_weights: models/UVH-26/weights/YOLOv11-X/UVH-26-MV-YOLOv11-X.pt
roi:
  count_direction: BOTH
  counting_line:
  - - 0
    - 0
  - - 0
    - 0
  reference_height: 1080
  reference_width: 1920
